"""Graph-integrity regression tests for every shipped example workflow.

ComfyUI's UI-format JSON is redundantly linked (the links array AND each
node's inputs[].link / outputs[].links must agree), and `widgets_values` is
positional — both have caused real shipped bugs (the 2026-07-06 widget-order
corruption; a hand-edited origin-links omission in the shot-cam workflow that
this test's first run caught). The staged master alone was hand-edited eight
times on 2026-07-11; every edit was validated by a throwaway copy of exactly
this checker. Promoted to a permanent test per the beta-0.3 spec-panel review
("highest value-per-line item"): no live ComfyUI needed, runs in milliseconds.
"""

import glob
import json
import os
import re

import pytest

from conftest import is_local_workflow

EXAMPLES_DIR = os.path.join(os.path.dirname(__file__), "..", "examples")

STAGED_MASTER = "atlas_camera_staged_master_workflow.json"
STAGED_AGENTIC = "atlas_camera_staged_master_agentic_assessment_workflow.json"
QUICKSTART_PAIRS = (
    ("atlas_input_quickstart_workflow.json",
     "atlas_input_quickstart_agentic_assessment_workflow.json"),
    ("atlas_occlusion_cull_quickstart_workflow.json",
     "atlas_occlusion_cull_quickstart_agentic_assessment_workflow.json"),
)

# ComfyUI frontend zod schema: workflow id is z.string().uuid().optional()
UUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")


def _ui_workflows():
    out = []
    for path in sorted(glob.glob(os.path.join(EXAMPLES_DIR, "*.json"))):
        if is_local_workflow(path):
            continue  # artist working copy — see conftest.is_local_workflow
        try:
            wf = json.load(open(path, encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        # UI format only — api-format exports and non-workflow JSON are skipped
        if isinstance(wf, dict) and isinstance(wf.get("nodes"), list) and "links" in wf:
            out.append((os.path.basename(path), wf))
    return out


_WORKFLOWS = _ui_workflows()


def test_examples_directory_has_ui_workflows():
    """The shipped catalogue, pinned by NAME so neither a deletion nor an
    unreviewed addition can pass unnoticed. Review = add the name here.

    Emptied 2026-07-31: the previous 21 were removed wholesale. They had grown
    by copying whole graphs and editing the tail, so 46 of 99 registered nodes
    appeared in NO example while AtlasBlockoutViewport appeared in 19 of 21.
    The replacement set is authored in the GUI and must execute green through
    tools/workflow_benchmark.py before landing — loading is not acceptance.

    Cut to FOUR for v1 (2026-08-07), then FIVE with the deterministic RAW
    multi-view workflow (2026-08-09), regenerated by
    tools/build_v1_shipping_workflows.py against a live /object_info. Each
    answers a different question — does it work / what are the stages / what do
    I get in my DCC / how do I matte-paint with it — and each runs on a fresh
    clone with a bundled plate and no gated node. Coverage was not the thing
    lost: 52 of 90 standard nodes already appeared in no example, so the
    guarantee being traded away did not exist. What WAS wrong is now gone: the
    old set shipped an ATLAS_EXPERIMENTAL node that loads red by default, and
    one that cannot run without a local VLM. The other eight moved to
    examples/local/ (gitignored, still on disk, still in history) and any can
    return once it is benchmark-green.
    """
    names = sorted(n for n, _ in _WORKFLOWS)
    assert names == ["atlas_blender_measured_primitives_workflow.json",
                     "atlas_burst_multiview_solve_workflow.json",
                     "atlas_burst_night_affinity_relight_workflow.json",
                     "atlas_burst_photographed_hole_patch_workflow.json",
                     "atlas_cleanplate_depth_layer_workflow.json",
                     "atlas_export_fanout_workflow.json",
                     "atlas_hero_02_photo_to_editable_scene_workflow.json",
                     "atlas_input_quickstart_workflow.json",
                     "atlas_layered_projection_workflow.json",
                     "atlas_multiview_raw_qwen_workflow.json",
                     "atlas_photo_to_atlas_scene_workflow.json",
                     "atlas_quickstart_solve_project_export_workflow.json",
                     "atlas_qwen_multiangle_hole_patch_workflow.json",
                     "atlas_qwen_roi_registered_patch_workflow.json",
                     "atlas_raw_affinity_cleanplate_workflow.json",
                     "atlas_raw_multiview_affinity_patch_workflow.json",
                     "atlas_raw_street_affinity_declutter_workflow.json",
                     "atlas_raw_to_atlas_scene_workflow.json",
                     "atlas_scene_measured_scale_workflow.json"]


@pytest.mark.parametrize("name,wf", _WORKFLOWS, ids=[n for n, _ in _WORKFLOWS])
def test_workflow_link_graph_is_bidirectionally_consistent(name, wf):
    """Every link must be listed by its origin output AND referenced by its
    target input, and every node-side link id must exist in the links array —
    the invariant every hand/script edit of a workflow must preserve."""
    nodes = {n["id"]: n for n in wf["nodes"]}
    errs = []
    links = wf.get("links") or []
    for link in links:
        assert isinstance(link, list) and len(link) >= 6, f"malformed link entry {link!r}"
        lid, oid, oslot, tid, tslot = link[:5]
        if oid not in nodes or tid not in nodes:
            errs.append(f"link {lid}: references missing node ({oid}->{tid})")
            continue
        outs = nodes[oid].get("outputs") or []
        ins = nodes[tid].get("inputs") or []
        if oslot >= len(outs) or lid not in (outs[oslot].get("links") or []):
            errs.append(f"link {lid}: origin {oid}:{oslot} does not list it")
        if tslot >= len(ins) or ins[tslot].get("link") != lid:
            errs.append(f"link {lid}: target {tid}:{tslot} does not reference it")
    link_ids = {link[0] for link in links}
    for n in wf["nodes"]:
        for inp in n.get("inputs") or []:
            if inp.get("link") is not None and inp["link"] not in link_ids:
                errs.append(f"node {n['id']}: dangling input link {inp['link']}")
        for out in n.get("outputs") or []:
            for lid in out.get("links") or []:
                if lid not in link_ids:
                    errs.append(f"node {n['id']}: dangling output link {lid}")
    assert not errs, f"{name}: " + "; ".join(errs[:10])


@pytest.mark.parametrize("name,wf", _WORKFLOWS, ids=[n for n, _ in _WORKFLOWS])
def test_workflow_id_counters_cover_contents(name, wf):
    """last_node_id / last_link_id must be >= every id in use — a stale
    counter makes the frontend mint DUPLICATE ids for newly added nodes."""
    node_ids = [n["id"] for n in wf["nodes"] if isinstance(n["id"], int)]
    link_ids = [link[0] for link in (wf.get("links") or [])
                if isinstance(link[0], int)]
    if node_ids and isinstance(wf.get("last_node_id"), int):
        assert wf["last_node_id"] >= max(node_ids), name
    if link_ids and isinstance(wf.get("last_link_id"), int):
        assert wf["last_link_id"] >= max(link_ids), name


def _staged():
    match = [wf for n, wf in _WORKFLOWS if n == STAGED_MASTER]
    assert match, "staged master workflow missing from examples/"
    return match[0]


def _staged_agentic():
    return _workflow(STAGED_AGENTIC)


def _workflow(name):
    match = [wf for workflow_name, wf in _WORKFLOWS if workflow_name == name]
    assert match, f"{name} missing from examples/"
    return match[0]


def _all_nodes(wf):
    nodes = list(wf.get("nodes") or [])
    for definition in (wf.get("definitions") or {}).get("subgraphs") or []:
        nodes.extend(definition.get("nodes") or [])
    return nodes


def _typed_edges(wf):
    nodes = {node["id"]: node for node in wf["nodes"]}
    edges = set()
    for _, origin_id, origin_slot, target_id, target_slot, *_ in wf["links"]:
        origin = nodes[origin_id]
        target = nodes[target_id]
        edges.add((origin["type"], origin["outputs"][origin_slot]["name"],
                   target["type"], target["inputs"][target_slot]["name"]))
    return edges


@pytest.mark.parametrize("name,wf", _WORKFLOWS, ids=[n for n, _ in _WORKFLOWS])
def test_workflow_id_is_a_uuid(name, wf):
    """The ComfyUI frontend validates loaded workflows against a zod schema
    whose top-level `id` is `z.string().uuid().optional()` — a human-readable
    slug raises the yellow toast "Invalid workflow against zod schema:
    Validation error: Invalid uuid at \"id\"". The graph still loads (the
    frontend falls back to the unvalidated data, `validatedGraphData ??
    graphData`) but it silently SKIPS the `tryFixLinks` repair pass, so a
    rejected workflow also loses the link-integrity fixups every other
    workflow gets. Three shipped quickstarts carried hand-written slugs
    ("atlas-input-quickstart"), two of them identical — found live 2026-07-21
    against the frontend bundled with ComfyUI 0.3.49, reproduced with a
    positive control. The key is optional — omitting it lets the frontend
    generate one — but every workflow here ships a stable id, so it must be a
    real UUID."""
    wf_id = wf.get("id")
    if wf_id is None:
        return  # omitted is valid: the frontend auto-generates
    assert UUID_RE.match(str(wf_id)), (
        f"{name}: workflow id {wf_id!r} is not a UUID — the frontend's zod "
        f"schema will reject this workflow on load")


def test_workflow_ids_are_unique():
    """Two quickstarts shipped the SAME id ("atlas-input-quickstart"), which
    would collide in the frontend's workflow store once both became valid
    UUIDs. Distinct ids are what make a stable id worth having at all."""
    ids = [wf["id"] for _, wf in _WORKFLOWS if wf.get("id") is not None]
    dupes = {i for i in ids if ids.count(i) > 1}
    assert not dupes, f"duplicate workflow ids: {sorted(dupes)}"


def test_multiview_raw_workflow_pins_photographed_registration_boundary():
    wf = _workflow("atlas_multiview_raw_qwen_workflow.json")
    nodes = {node["id"]: node for node in wf["nodes"]}
    typed_edges = _typed_edges(wf)

    assert all(UUID_RE.match(str(node_id)) for node_id in nodes)
    assert [node["type"] for node in wf["nodes"]].count("AtlasLoadRAW") == 3
    assert [node["type"] for node in wf["nodes"]].count("AtlasMultiViewSolve") == 1
    assert [node["type"] for node in wf["nodes"]].count("AtlasAddPatchView") == 1
    assert ("AtlasMultiViewSolve", "solve", "AtlasAddPatchView", "solve") in typed_edges
    assert ("LoadImage", "IMAGE", "AtlasAddPatchView", "patch_image") in typed_edges

    registration = next(node for node in nodes.values()
                        if node["type"] == "AtlasMultiViewSolve")
    assert registration["widgets_values"] == ["auto", 1.43, "balanced", 0, "fixed", False, 0.0, False, "auto"]
    inbound = [link for link in wf["links"] if link[3] == registration["id"]]
    assert {nodes[link[1]]["type"] for link in inbound} == {"AtlasLoadRAW"}

    patch = next(node for node in nodes.values() if node["type"] == "AtlasAddPatchView")
    assert patch["mode"] == 4  # optional branch ships bypassed until Qwen imagery exists

    report_group = next(group for group in wf["groups"]
                        if "REGISTERED VIEWPORT" in group["title"])
    assert "CANONICAL" not in report_group["title"]
    assert "SCENE / DEBUG REPORT" in report_group["title"]


def test_multiview_raw_workflow_preserves_positional_widget_order():
    wf = _workflow("atlas_multiview_raw_qwen_workflow.json")
    expected = {
        "AtlasLoadRAW": [
            "file_path", "undistort", "half_size", "white_balance", "exposure_ev",
            "write_exr", "output_dir", "colorspace", "headroom",
        ],
        "AtlasMultiViewSolve": [
            "capture_mode", "camera_height_m", "match_quality", "seed",
            "learned_anchor_fallback", "baseline_m", "learned_scale_fallback",
            "pair_topology",
        ],
        "AtlasAddPatchView": [
            "patch_azimuth_view", "patch_elevation_view", "patch_distance",
            "source_azimuth_view", "source_elevation_view", "flip_azimuth", "name",
            "depth_model", "relief_grid", "priority", "device", "mask_unseen_only",
            "unseen_dilate_px", "geometry_source",
            # APPENDED 2026-08-16: measured patch camera (register_to_primary).
            "camera_source", "registration_min_inliers", "registration_max_residual_m",
            "registration_max_deviation_deg", "auto_flip_azimuth",
        ],
        "AtlasBlockoutViewport": [
            "resolution", "client_data", "preview_expand", "drawn_fill_px",
        ],
        "AtlasDebugReport": ["file_path"],
    }
    for node in wf["nodes"]:
        if node["type"] not in expected:
            continue
        widget_names = [
            item["widget"]["name"] for item in node["inputs"] if "widget" in item
        ]
        assert widget_names == expected[node["type"]], node["type"]
        phantom_seed_control = int(node["type"] == "AtlasMultiViewSolve")
        assert len(node["widgets_values"]) == len(widget_names) + phantom_seed_control
