"""
Maya export — produces Maya ASCII (.ma) text for a recovered LatentCamera.

Target convention: Maya is left-handed-on-screen but uses a right-handed
world with +Y up, camera looking down -Z. Atlas core is OpenCV-convention
(+Y down, looks +Z). The remap applied here, and ONLY here
(DECISIONS.md §1):

    maya_x =  cv_x
    maya_y = -cv_y
    maya_z = -cv_z

All physical-unit conversions (mm -> inches, px -> normalized film offset)
go through atlas.core.camera_math — never computed locally in this module
(DECISIONS.md §2).

Node names below are the FROZEN canonical interface (DECISIONS.md §4).
Do not rename without a schema_version bump and a migration note.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from atlas.core import camera_math

if TYPE_CHECKING:
    from atlas.core.latent_camera import LatentCamera

# Frozen node names — vision document's convention won the naming
# conflict (DECISIONS.md §4).
NODE_CAMERA = "atlas_CAMERA"
NODE_PROJECTION_GRP = "atlas_PROJECTION_GRP"
NODE_GEOMETRY_GRP = "atlas_GEOMETRY_GRP"
NODE_DEBUG_GRP = "atlas_DEBUG_GRP"
NODE_REFERENCE_GRP = "atlas_REFERENCE_GRP"


def _remap_point_to_maya(cv_xyz: tuple[float, float, float]) -> tuple[float, float, float]:
    """OpenCV (+Y down, looks +Z) -> Maya (+Y up, looks -Z)."""
    x, y, z = cv_xyz
    return (x, -y, -z)


def export_latent_camera(camera: "LatentCamera", *, camera_name: str | None = None) -> str:
    """Build Maya ASCII (.ma) text for `camera`.

    Returns the full file text; callers write it to disk. Returning text
    rather than writing a file directly keeps this function pure and
    testable (see tests/test_exports.py — Maya value conversion test
    parses this output rather than touching the filesystem).
    """
    cam_node = camera_name or NODE_CAMERA

    aperture_w_in = camera_math.mm_to_inches(camera.sensor_width_mm)
    aperture_h_in = camera_math.mm_to_inches(camera.sensor_height_mm)

    pp_x, pp_y = camera.principal_point_px
    offset_x_norm = camera_math.px_to_normalized_offset(
        pp_x - camera.image_width / 2.0,
        camera.sensor_width_mm,
        camera.image_width,
        camera.focal_length_mm or 1.0,
    )
    offset_y_norm = camera_math.px_to_normalized_offset(
        pp_y - camera.image_height / 2.0,
        camera.sensor_height_mm,
        camera.image_height,
        camera.focal_length_mm or 1.0,
    )

    focal_mm = camera.focal_length_mm
    if focal_mm is None:
        raise ValueError(
            "Cannot export to Maya without a focal length. Use "
            "LatentCamera.with_estimated_focal(...) to derive one from "
            "FOV before exporting."
        )

    translation = camera.translation or (0.0, 0.0, 0.0)
    maya_translation = _remap_point_to_maya(translation)

    rotation = camera.rotation_euler or (0.0, 0.0, 0.0)
    # Euler angle remap follows the same axis-sign flip as translation,
    # applied per-axis to pitch/yaw (X/Y); roll (Z) sign convention
    # depends on rotation order and is intentionally left as a TODO for
    # the full rotation-order-aware implementation — flagged in notes
    # below rather than silently assumed.
    maya_rotation = (rotation[0], -rotation[1], rotation[2])

    inferred_tag = " (~EST, inferred)" if camera.focal_inferred else ""

    lines = [
        f'//Maya ASCII — generated by Atlas v{camera.schema_version}',
        f'//LatentCamera export — coordinate_convention: {camera.coordinate_convention} -> maya',
        f'createNode transform -n "{cam_node}";',
        f'createNode camera -n "{cam_node}Shape" -p "{cam_node}";',
        f'\tsetAttr ".focalLength" {focal_mm:.6f}{_comment(inferred_tag)}',
        f'\tsetAttr ".horizontalFilmAperture" {aperture_w_in:.6f};',
        f'\tsetAttr ".verticalFilmAperture" {aperture_h_in:.6f};',
        f'\tsetAttr ".horizontalFilmOffset" {offset_x_norm:.6f};',
        f'\tsetAttr ".verticalFilmOffset" {offset_y_norm:.6f};',
        f'setAttr "{cam_node}.translate" -type "double3" '
        f'{maya_translation[0]:.6f} {maya_translation[1]:.6f} {maya_translation[2]:.6f};',
        f'setAttr "{cam_node}.rotate" -type "double3" '
        f'{maya_rotation[0]:.6f} {maya_rotation[1]:.6f} {maya_rotation[2]:.6f};',
        f'createNode transform -n "{NODE_PROJECTION_GRP}";',
        f'createNode transform -n "{NODE_GEOMETRY_GRP}";',
        f'createNode transform -n "{NODE_DEBUG_GRP}";',
        f'createNode transform -n "{NODE_REFERENCE_GRP}";',
    ]

    if camera.focal_inferred:
        lines.insert(1, f'//WARNING: focal_length_mm was inferred, not '
                         f'directly recovered — see LatentCamera.notes')

    return "\n".join(lines) + "\n"


def _comment(tag: str) -> str:
    return f"  //{tag}" if tag else ""
