"""Generate docs/shoot_project.example.json — the iOS app's test fixture.

The example is GENERATED, not hand-written, so it cannot drift from what
`AtlasShootList` actually emits. `tests/test_shoot_list.py` regenerates it and
compares, the same discipline the feature audit uses.

It matters more than a normal doc sample: the iOS app is built on a different
machine, in a different language, against this file. If it stops matching
reality, that is discovered on the Mac — late, and confusingly.

Regenerate:  python tools/build_shoot_example.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "shoot_project.example.json"


def build() -> dict:
    """A city street: pavement behind a parked car, a facade behind a tree, an alley.

    Deliberately covers all three cases the app must handle — a near planar
    surface, a far planar surface, and a VOLUMETRIC one with no plane at all,
    which is the case that needs AR alignment instead of a flat texture.
    """
    import atlas_camera.core.schema as sch
    from atlas_camera.core.camera_math import look_at_view_matrix
    from atlas_camera.core.intrinsics import build_intrinsics
    from atlas_camera.core.occlusion_graph import (
        AtlasOcclusionGraph,
        OcclusionEdge,
        OcclusionNode,
    )
    from atlas_camera.core.shoot_list import build_shoot_list, shoot_project

    graph = AtlasOcclusionGraph(version=1, notes=[], nodes=[
        OcclusionNode(id="pavement", kind="ground",
                      plane={"normal": [0, 1, 0], "d": 0.0},
                      depth_range_m=(3.5, 14.0), completion_policy="extend_plane",
                      texture_policy="edge_dilate", confidence=0.82),
        OcclusionNode(id="facade_left", kind="surface",
                      plane={"normal": [1, 0, 0], "d": -6.0},
                      depth_range_m=(8.0, 18.0), completion_policy="extend_plane",
                      texture_policy="edge_dilate", confidence=0.71),
        OcclusionNode(id="alley", kind="object", plane=None,
                      depth_range_m=(12.0, 30.0),
                      completion_policy="conservative_proxy", confidence=0.44),
    ], edges=[
        OcclusionEdge(occluder="parked_car", occludee="pavement", tear_pixels=21000),
        OcclusionEdge(occluder="bollard", occludee="pavement", tear_pixels=1800),
        OcclusionEdge(occluder="street_tree", occludee="facade_left", tear_pixels=9400),
        OcclusionEdge(occluder="corner_wall", occludee="alley", tear_pixels=15200),
    ])

    class _Plan:
        def __init__(self, nid, concepts):
            self.node_id, self.concepts, self.needs_clean_plate = nid, concepts, True

    plans = [_Plan("pavement", ["pavement", "kerb"]),
             _Plan("facade_left", ["brick wall", "shopfront"]),
             _Plan("alley", ["alleyway"])]

    view, world, rot = look_at_view_matrix(eye=(0, 1.6, 0), target=(0, 1.6, -1),
                                           up=(0, 1, 0))
    intr = build_intrinsics(image_width=4000, image_height=3000,
                            focal_length_mm=35.0, sensor_width_mm=36.0)
    extr = sch.AtlasExtrinsics(camera_position=(0.0, 1.6, 0.0),
                               camera_rotation_matrix=rot,
                               camera_world_matrix=world, camera_view_matrix=view)
    solve = sch.AtlasSolve(camera=sch.AtlasCamera(intrinsics=intr, extrinsics=extr),
                           image_path="city_street.jpg",
                           image_width=4000, image_height=3000)

    specs = build_shoot_list(solve, graph, layer_plan=plans)
    return shoot_project(specs, plate_size=(4000, 3000), notes=[
        "EXAMPLE fixture, generated by tools/build_shoot_example.py.",
        "A real project is written next to reference_plate.png by AtlasShootList.",
    ])


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
