"""ComfyUI node library for Atlas Camera — compatibility façade.

The original 9,110-line module was split into responsibility modules
(node_helpers, nodes_solve, nodes_depth, nodes_geometry, nodes_inpaint,
nodes_export, nodes_viewport) and node_registry. This façade re-exports
every node class, shared helper, and the registry mappings so that
``from atlas_camera.comfy.nodes import X`` and saved ComfyUI workflows
keep working unchanged. New code should import from the specific module.

Every import below is a deliberate re-export — "unused" is the whole point,
and `tests/test_facade_surface.py` pins the resulting surface. Silenced once
here rather than per line, so a genuinely dead import elsewhere still shows up.
"""
# ruff: noqa: F401
from __future__ import annotations

from atlas_camera.comfy.nodes_project import AtlasProject  # noqa: F401
from atlas_camera.comfy.nodes_multiview import (  # noqa: F401
    AtlasMultiViewSolve,
    AtlasMultiViewSolveBurst,
    AtlasSolveBurstPatchCrops,
)

from atlas_camera.comfy.viewport_payload import (  # noqa: F401
    _fit_long_edge,
    _plate_ref_to_dict,
    _output_profile_to_dict,
    _extract_blockout_camera,
)
from atlas_camera.comfy.node_helpers import (
    _DEPTH_MODEL_CHOICES,
    _MOGE_NORMAL_MODEL_CHOICES,
    _ATLAS_BLOCKOUT_CACHE,
    _ATLAS_BLOCKOUT_CACHE_MAX,
    _blockout_cache_set,
    _solve_focal_px_for_image,
    _require_numpy,
    _require_torch,
    _require_pil,
    _image_tensor_to_pil,
    _pil_to_image_tensor,
    _save_image_tensor_to_tmp,
    _resolve_raw_hints,
    _scale_summary_suffix,
    _IDENTITY_COMMENT_PREFIX,
    _write_export_manifest,
    _health_summary_suffix,
    _stamp_raw_provenance,
    _extend_edge_colors,
    _b64_png_to_mask,
    _mask_to_b64_png,
    _image_tensor_to_preview_b64,
    _clone_solve_with_metadata,
    _decode_b64_to_tensor,
    _image_fingerprint,
    _solve_fingerprint,
    _execution_blocker,
    _ground_depth_compute,
    _reference_id_choices,
    _extrinsics_from_view,
    _recompute_horizon_line,
    _ATLAS_ASSESS_CACHE,
    _solve_camera_params,
    _horizon_y_from_solve,
    _depth_map_for_solve,
    _replace_proxy_role_geometry,
    _MetricDepthSetup,
    _BORDER_FLOOD_PX,
    _flood_mask_to_frame_borders,
    _resolve_exclude_mask,
    _GROUND_SCALE_CACHE,
    _ground_scale_cached,
    _metric_depth_and_validity,
    _resolve_depth_band,
    _parse_band_override,
    _band_resolution_validity,
    _resize_normal_field,
    _AZIMUTH_VIEWS,
    _ELEVATION_VIEWS,
    _DISTANCE_VIEWS,
    _parse_view_prompt,
    _parse_exact_view,
    _parse_exact_pivot,
    _format_exact_view,
    _named_view_orbit_delta,
    _format_hole_fill_report,
    _solve_with_relief_mesh,
    _relief_mesh_from_solve,
    _solve_image_size,
    _apply_band_split,
    _BOUNDED_BAND_NOOP_M,
    _LAYER_DEBUG_PRIMARY_HEX,
    _LAYER_DEBUG_PALETTE_HEX,
    _comfy_registry,
    _native_sam3_available,
    _MiniGraphBuilder,
    _graph_builder,
    _ATLAS_INPUT_BOUNDARIES,
    _ATLAS_INPUT_BAND_NAMES,
    _seg_coverage,
    _BAND_GEOMETRY_CHOICES,
    _resolve_band_geometry,
    _analytic_ground_forward_depth,
)
from atlas_camera.comfy.nodes_viewport import (
    AtlasViewportControls,
    AtlasBlockoutViewport,
    AtlasStereoRender,
    AtlasDebugReport,
    AtlasLayerPreview,
    AtlasInput,
    AtlasDisocclusionGuide,
)
from atlas_camera.comfy.nodes_completion import (
    AtlasCompleteDepth,
    AtlasLayerPlan,
    AtlasMoveBudget,
    AtlasOcclusionGraph,
    AtlasShootList,
)
from atlas_camera.comfy.nodes_qa import AtlasAssessOutput
from atlas_camera.comfy.nodes_dynamic import AtlasLoadDynamicPlate
from atlas_camera.comfy.nodes_hidden_volume import AtlasLoadHiddenVolume  # noqa: F401
from atlas_camera.comfy.nodes_agent import AtlasAgentHandoff  # noqa: F401
from atlas_camera.comfy.nodes_fill import (AtlasCameraMovePreset,
                                           AtlasCompositeCrop,
                                           AtlasCropROI,
                                           AtlasCropSourcePhoto,
                                           AtlasInterpassGate,
                                           AtlasMembraneComposite,
                                           AtlasPathFrameIndex)
from atlas_camera.comfy.nodes_solve import (
    AtlasLoadPlate,
    AtlasRegisterPlate,
    AtlasDeband,
    AtlasGrade,
    AtlasDefocus,
    AtlasApplyLUT,
    AtlasAttachSourcePlate,
    AtlasLoadRAW,
    AtlasSolveFromImage,
    AtlasConstrainedSolve,
    AtlasLearnedSolveFromImage,
    AtlasScaleOverride,
    AtlasRollTrim,
    AtlasGravityOverride,
    AtlasGravityCompass,
    AtlasReferenceScaleSolve,
    AtlasAssessImage,
    AtlasSolveGate,
    AtlasSceneHealthGate,
    AtlasVLMScaleCues,
    AtlasApplyScaleReferences,
    AtlasFaceScaleReference,
    AtlasLoadRecord3D,
    AtlasSplitEquirect,
    AtlasEquirectMultiView,
    AtlasLoadSolveJSON,
    AtlasDecomposeSolve,
    AtlasDecomposeCamera,
    AtlasUSDCameraLoader,
    AtlasStreamRecord3D,
)
from atlas_camera.comfy.nodes_depth import (
    AtlasDepthAnything,
    AtlasDepthMap,
    AtlasDepthOutlierMask,
    AtlasMogeNormals,
    AtlasDepthDetailEnhance,
    AtlasDepthCombine,
    AtlasDepthBandSplit,
    AtlasBoundedBand,
    AtlasDepthLayerMask,
    AtlasGroundDepthMap,
    AtlasGroundMask,
    AtlasHorizonMask,
    AtlasVPVisualization,
    AtlasOutpaintDepth,
    AtlasFitDepthCalibration,
    AtlasApplyDepthCalibration,
)
from atlas_camera.comfy.nodes_geometry import (
    AtlasDeriveProjectionGeometry,
    AtlasDeriveReliefMesh,
    AtlasLiveMeshRepair,
    AtlasRetopologizeLayer,
    AtlasPlanarHolePatch,
    AtlasMaskedSurfaceReconstruct,
    AtlasRefineOcclusionSeams,
    AtlasPathGuidedHoleRepair,
    AtlasDeriveWalls,
    AtlasDeriveTowersSpires,
    AtlasDeriveRoofsFacades,
    AtlasDeriveInteriorRoom,
    AtlasGroundPlane,
    AtlasMergeGeometry,
    AtlasDefineShotCam,
    AtlasExtractAnglePatch,
    AtlasImportAnglePatch,
    AtlasAddPatchView,
    AtlasOcclusionMask,
    AtlasSolvePatchViews,
    AtlasBlockoutMassing,
    AtlasBlenderImportMeshes,
    AtlasBlenderMassing,
)
from atlas_camera.comfy.nodes_inpaint import (
    AtlasScopeMask,
    AtlasSemanticMask,
    AtlasSAM3Mask,
    AtlasInpaintCrop,
    AtlasInpaintStitch,
    AtlasSDXLInpaint,
    AtlasInstanceMask,
    AtlasCardMask,
    AtlasSegmentedSDXLInpaint,
    AtlasCleanPlateLayer,
    AtlasPlateLayer,
    AtlasCleanPlateStack,
    AtlasSkyDomeLayer,
)
from atlas_camera.comfy.nodes_export import (
    AtlasExportReviewPackage,
    AtlasExportScenePackage,
    AtlasExportSolveJSON,
    AtlasExportMayaReviewScene,
    AtlasExportReliefMesh,
    AtlasExportUSD,
    AtlasExportBlender,
    AtlasExportNuke,
    AtlasExportNukeLayers,
    AtlasExportMayaLayers,
    AtlasExportCameraPathUSD,
    AtlasExportPlateEXR,
)
from atlas_camera.comfy.nodes_world_plate import (
    AtlasOpenRealPlate,
    AtlasReadLockedPlatePlan,
    AtlasRecordPlateAttempt,
    AtlasExportPlateHandoff,
    AtlasRealPlateToScene,
)

from atlas_camera.comfy.node_registry import (
    NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS,
    EXPERIMENTAL_NODE_CLASS_MAPPINGS,
    EXPERIMENTAL_NODE_DISPLAY_NAME_MAPPINGS,
    ATLAS_EXPERIMENTAL_DEFAULT,
    _experimental_enabled,
    LEGACY_NODE_CLASS_MAPPINGS,
    LEGACY_NODE_DISPLAY_NAME_MAPPINGS,
    LEGACY_REPLACEMENTS,
    ATLAS_LEGACY_DEFAULT,
    _legacy_enabled,
    IOS_NODE_CLASS_MAPPINGS,
    IOS_NODE_DISPLAY_NAME_MAPPINGS,
    ATLAS_IOS_DEFAULT,
    _ios_enabled,
)
